### ISSUE TITLE
some es7 class method will not copy to the wrapcomponent

### ISSUE THREAD

**Issue by treemore** [elado/hoist-non-react-methods#7]
because  the method like 
```js
 boundFunction = () => {
      return this.instanceProperty;
    }
```
boundFunction will not present in the Bork prototype. 
i use this lib ,but found some method always undefined. 
maybe this issue will help the other people use this lib.
Although this issue has nothing to do with this library,

https://babeljs.io/docs/plugins/transform-class-properties/
```js
class Bork {
    //Property initializer syntax
    instanceProperty = "bork";
    boundFunction = () => {
      return this.instanceProperty;
    }

    //Static class properties
    static staticProperty = "babelIsCool";
    static staticFunction = function() {
      return Bork.staticProperty;
    }
  }

  let myBork = new Bork;

  //Property initializers are not on the prototype.
  console.log(myBork.__proto__.boundFunction); // > undefined
```

**Comment by treemore** [comment]
Just make a mark, because this problem has troubled me for hours

**Comment by elado** [comment]
Please see my note in the readme about the new recommendations.
